[package]
name = "dvf"
version = "0.1.0"
authors = ["Zico <zhicong303@gmail.com"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miracl_core = {version = "2.7.0", features = ["bls12381"]}
lazy_static = "1.4.0"
num-bigint = {version = "0.4.0", features = ["rand"]}
rand = "0.8.4"
num-traits = "0.2.8"
array-init = "2.0.0"
